const books = [
  {
    id: 1,
    title: "Belajar JavaScript Dasar",
    author: "Andi Prasetyo",
    year: 2021,
    price: 89000,
    category: "JavaScript",
    description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
    image: "https://covers.openlibrary.org/b/id/8739161-L.jpg",
  },
  {
    id: 2,
    title: "React untuk Pemula",
    author: "Dina Sari",
    year: 2022,
    price: 115000,
    category: "React",
    description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
    image: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
  },
  {
    id: 3,
    title: "Menguasai Node.js",
    author: "Budi Santoso",
    year: 2022,
    price: 99000,
    category: "Backend",
    description: "Membangun server dan REST API handal menggunakan Node.js dan Express.",
    image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
  },
  {
    id: 4,
    title: "CSS & Tailwind Modern",
    author: "Rina Marlina",
    year: 2023,
    price: 79000,
    category: "CSS",
    description: "Panduan styling web profesional dengan CSS dan Tailwind CSS.",
    image: "https://covers.openlibrary.org/b/id/9255566-L.jpg",
  },
  {
    id: 5,
    title: "TypeScript Komprehensif",
    author: "Maya Putri",
    year: 2023,
    price: 125000,
    category: "TypeScript",
    description: "Kuasai TypeScript untuk membangun aplikasi yang lebih aman dan terstruktur.",
    image: "https://covers.openlibrary.org/b/id/10776603-L.jpg",
  },
  {
    id: 6,
    title: "Database dengan PostgreSQL",
    author: "Doni Kurniawan",
    year: 2021,
    price: 95000,
    category: "Database",
    description: "Belajar merancang dan mengelola database relasional menggunakan PostgreSQL.",
    image: "https://covers.openlibrary.org/b/id/8739162-L.jpg",
  },
  {
    id: 7,
    title: "Git & GitHub untuk Developer",
    author: "Sari Dewi",
    year: 2022,
    price: 69000,
    category: "Tools",
    description: "Kuasai version control dan kolaborasi tim menggunakan Git dan GitHub.",
    image: "https://covers.openlibrary.org/b/id/8091017-L.jpg",
  },
  {
    id: 8,
    title: "Vue.js dari Dasar",
    author: "Andi Prasetyo",
    year: 2023,
    price: 109000,
    category: "Vue",
    description: "Membangun aplikasi web interaktif dengan framework Vue.js 3.",
    image: "https://covers.openlibrary.org/b/id/10521271-L.jpg",
  },
  {
    id: 9,
    title: "Python untuk Data Science",
    author: "Budi Santoso",
    year: 2023,
    price: 135000,
    category: "Python",
    description: "Analisis data dan machine learning menggunakan Python dan library populer.",
    image: "https://covers.openlibrary.org/b/id/9255567-L.jpg",
  },
]

export default books
